### ISSUE TITLE
Gemfile.lock記載のバージョンとRuby標準添付のバージョン違いによる、digestに関するエラー

### ISSUE THREAD

**Issue by ntee** [tdiary/tdiary-core#1030]
レンタルサーバ（XREA）でver. 5.2.1以降にすると以下のエラーが発生します。
Could not find digest-3.1.0 in any of the sources (Bundler::GemNotFound)
5.2.0では発生しません。

Rubyのバージョンは
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]

https://github.com/tdiary/tdiary-core/commit/2cc5a7748dd1f93be5ad298877e07f7fdac3b180
このコミットでGemfile.lockに digest (3.1.0) が追記されていますが、ruby 3.0ではdigestが3.0.0のためでしょうか。
Gemfile.lockの記述を digest (3.0.0) に修正すると動きます。

よい解決策はわからないので、ひとまずイシューたてだけです。

**Comment by tdtds** [comment]
ふむぅ。`digest` gem が default gem になったからですねぇ。これはどう解消するのがいいのかな……。`bundle update` はひとつの手だけど、CGI でちゃんと動作するかは確認しないとわからないですね

**Comment by ntee** [comment]
bundle update を実行してみたら digest 3.1.0 がインストールされましたが、

You have already activated digest 3.0.0, but your Gemfile requires digest 3.1.0. 
Since digest is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports digest as a default gem. (Gem::LoadError)

となって、やっぱり動きませんでした。

**Comment by tdtds** [comment]
うーん、やっかいだな、default gem……。

**Comment by hsbt** [comment]
見ときます

**Comment by hsbt** [comment]
`net-smtp` 自体はもう digest の依存が外れているので net-smtp の新しいやつをリリースすれば良さそうな気がします。

それはそれとして `digest` に積極的に依存する理由もないので `OpenSSL::Digest` を使うように置き換えた PR を出しときました。 https://github.com/ruby/net-smtp/pull/43

**Comment by tdtds** [comment]
はー、なるほど。そういう罠か～

**Comment by hsbt** [comment]
ひとまず net-smtp-0.3.2 を出したので lockfile を更新すれば digest の version conflict は解決すると思います。

**Comment by ntee** [comment]
ver. 5.2.3 の展開先で bundle update net-smtp を実行することで Gemfile.lock が更新されて、tDiary が動くようになりました。

**Comment by hsbt** [comment]
お手数おかけしました〜
