### ISSUE TITLE
DockerコンテナでRack::Lint::LintErrorが発生する

### ISSUE THREAD

**Issue by iwamot** [tdiary/tdiary-core#1050]
**Describe the bug / 不具合の説明**

DockerコンテナでRack::Lint::LintErrorが発生する。

**To Reproduce / 再現手順**

1. git clone https\://github.com/tdiary/tdiary-core
2. cd tdiary-core
3. docker build -t tdiary .
4. docker run -it --rm -p 9292:9292 tdiary
5. http\://localhost:9292/ にアクセスする

**Expected behavior / 期待した動作**

初期ページが正常表示される。

**Screenshots / スクリーンショット**

![Rack::Lint::LintError](https://user-images.githubusercontent.com/16149/203713928-984c3b06-f62c-49af-9dbd-663cabb6205d.png)

**Environment / 動作環境**

 - tDiary Version: 5.2.3

**Additional context**

rack 3.0のリリースにより、大文字を含むHTTPヘッダキーがエラー扱いとなりました。https://github.com/rack/rack/issues/1592

ただし、RACK_ENVをdeploymentにすれば、Rack::Lintを通らずエラーになりません。

**Comment by tdtds** [comment]
教えていただいて、ありがとうございます～。
今日これからリリースなんですが、ちょっと直すには影響が大きすぎるので、とりあえず今回は `RACK_ENV=deplotment` で出します。
ちゃんと直すまでこの issue は open にしておきます🙇‍♂️

**Comment by tdtds** [comment]
ちなみに、あらゆる `Content-Type` を `content-type` に置換しただけでは(さらに謎いエラーが出て)動きませんでした。とほほ。
