### ISSUE TITLE
5.2.5 リリース作業 on 2024-02-XX

### ISSUE THREAD

**Issue by tdtds** [tdiary/tdiary-core#1055]
リリース作業リスト
- [x] lib/tdiary/tasks/release.rake` と `.github/workflow/ci.yml` に今回サポートを追加/停止するrubyのバージョンが含まれるか確認、修正する
- [x] [releases](https://github.com/tdiary/tdiary-core/releases)にエントリを追加してリリースノートを書く
- [x] coreおよびblogkitのChangeLogに「release L.M.N」のエントリを追加する
- [x] 以下のファイルのバージョンをあげてcommitする
  - coreの lib/tdiary/version.rb
  - blogkitの lib/tdiary/blogkit/version.rb
  - contribの lib/tdiary/contrib/version.rb
- [x] core / blogkit / contrib / theme に tag を打つ (`git pull --tags; git tag vL.M.N; git push origin vL.M.N`)
- [x] 以下の各リポジトリ配下で`bundle clean; bundle exec rake release` コマンドを実行する (gemを最新にしてrubygemsにアップロード)
  - core
  - blogkit
  - contrib
- [x] core配下で`bundle exec rake package:stable package:release` コマンドを実行する(GitHub に tar.gz をアップロードする。GITHUB_ACCESS_TOKEN環境変数が必要なので注意, see #573)
- [x] themeのmasterブランチをgh-pagesブランチへmerge、pushする (`git checkout gh-pages; git merge master; git push origin gh-pages`)
- [x] core配下で `docker build . -t tdiary/tdiary:L.M.N` を実行してから、`push` する (`L.M`, `L`, `latest` も同様)
- [x] tdiary.org の以下のエントリーを書く
  - [ダウンロード](https://github.com/tdiary/tdiary.github.io/blob/master/download.md)
  - [サイドバー](https://github.com/tdiary/tdiary.github.io/blob/master/_includes/sidebar.html)
  - [リリースしましたのエントリ](https://github.com/tdiary/tdiary.github.io/tree/master/_posts) (`YYYY-MM-DD-release-L_M_N.md` 形式で)
- [x] 3ヶ月後の次のリリースの [issue](https://github.com/tdiary/tdiary-core/issues/new) と [project](https://github.com/orgs/tdiary/projects/new) を作る

**Comment by tdtds** [comment]
今日ちょっと忙しいので、4日ほどリリースを延期します。3/3に作業できる見込み。

**Comment by tdtds** [comment]
rack を 3 以上にあげると omniauth が 2.x 以上を要求してくるんだけど、2.x から (CSRF 対策で) GET を使えなくなったので、POST 用のページを一個挟むように改造しないといけない。という感じなので、こいつが release block になっています。もうちょっと粘るので2月のリリースはさらに遅れそう。

**Comment by hsbt** [comment]
>2.x から (CSRF 対策で) GET を使えなくなったので、POST 用のページを一個挟むように改造しないといけない。という感じ

omniauth の commit log 眺めたところ、warn のみ、のように見えました。

https://github.com/omniauth/omniauth/pull/1010

>OmniAuth.config.request_validation_phase

に nil を入れるとダメな感じですがリリースブロックは回避できそう?

**Comment by tdtds** [comment]
マ!? 読み落としてたか……
それでいきますかー。半年出さないわけにいかないもんねぇ

**Comment by hsbt** [comment]
ひとまず、ゆるパッチをあてて更新したのを https://github.com/tdiary/tdiary-core/pull/1097 に置きました。

**Comment by tdtds** [comment]
今日はちょっと無理っぽいけど、明日確認して(できれば)リリースします～

**Comment by hsbt** [comment]
2/28 にできるかは怪しいけど、Ruby 3.3 対応も含めて少し頑張ってみます

**Comment by hsbt** [comment]
memcached については、30days 触らないとサービス自体が停止するものだったので再度有効にしてみました。

```
path="/update.rb/auth/failure/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter/auth/twitter"
```

という形で redirect loop がどこかで起きているので調べてます。

**Comment by hsbt** [comment]
https://github.com/tdiary/tdiary-core/pull/1135 で Rack 3 対応のコードを revert したものの再現するので Twitter app が suspend してるとかそっちじゃないかなあ。redirect loop するのはそれはそれで問題ではあるが...

**Comment by hsbt** [comment]
https://github.com/tdiary/heroku-buildpack-tdiary で Google か GitHub を使うようにしてみます。

**Comment by hsbt** [comment]
GitHub に oauth を切り替えたところ、Rack 3 でも動作確認できたので 5.3.0 としてリリースします。

**Comment by hsbt** [comment]
https://tdiary.org/20240229.html リリースしました。大成功!
