### ISSUE TITLE
heroku preview app 設定の無効化と削除

### ISSUE THREAD

**Issue by hsbt** [tdiary/tdiary-core#1072]
https://github.com/tdiary/tdiary-core/pull/1070 など、heroku のプラン変更に伴って、review apps が軒並み fail しているようです。

@tdtds 

この辺、継続利用の計画がなければまとめて削除してしまおうと思いますが、どうでしょうか?

**Comment by tdtds** [comment]
いちおう eco dyno は有効にしてあるので、pipeline は動くはず。現状 fail しているのは heroku 用の Gemfile.lock が最新化されてないからだと思います。こないだ Rack 3.0 で動くようにしてもらったので、heroku でも動くようにできるはず。
時間みつけて直すので、しばらく放置しておいてもらってOKっす。

**Comment by hsbt** [comment]
プラン変更が要因ではない、ってことで理解しました。継続利用する、ということで大丈夫です!
