### ISSUE TITLE
plugin から CGI.new を撤去したい

### ISSUE THREAD

**Issue by hsbt** [tdiary/tdiary-core#15]
今後、内部構造を変化させていく時に影響が大きいので CGI.new せずに機能を実現できる方向で対応する。

対象は以下のプラグイン
category.rb, recent_comment3.rb, recent_list.rb, recent_trackback3.rb, squeeze.rb

**Comment by machu** [comment]
squeeze.rb以外は #467 で対応しました。squeeze.rbはTDiarBaseを継承しているので、内部構造を変化させるまではこのままですかね。

**Comment by tdtds** [comment]
squeezeはまだ利用価値のあるプラグインか、という命題がありそうだw

**Comment by machu** [comment]
squeeze.rbを廃止してクローズしましょうか。

**Comment by hsbt** [comment]
contrib 送りにして close ってのに 1 票です

**Comment by tdtds** [comment]
あー、それでいいかもですね。そうしましょう。

**Comment by tdtds** [comment]
次回のリリースまでにその方向で。

**Comment by hsbt** [comment]
misc/plugin から `CGI.new` はいなくなりました。

**Comment by tdtds** [comment]
:100:
