### ISSUE TITLE
カテゴリ画面に「設定」の「ヘッダ・フッタ」が反映されない

### ISSUE THREAD

**Issue by kdmsnr** [tdiary/tdiary-core#189]
その結果、サイドバーが消えるなどの症状が出ている。（例） http://sho.tdiary.net/?category=ebook

この場合はサイドバーも消えたほうがいいのかもしれないが、
日記画面を見ながらデザインを調整してもカテゴリ画面だけがくずれる、といったことが発生する可能性がある。

**Comment by tdtds** [comment]
長らく放置でしたが、カテゴリページのヘッダ/フッタは現状を仕様とし、closeします。

次々回のリリースでcategory.rbはよりシンプルに仕様を整理したものに置き換えますが(現時点ではcontrib/category-lite.rbとして存在)、ヘッダ/フッタに関してはさらに指定できる範囲を減らします。
