### ISSUE TITLE
og 系のヘッダを設定可能にする

### ISSUE THREAD

**Issue by hsbt** [tdiary/tdiary-core#244]
facebook と仲良く出来る何かをもう少し調べて実装する

**Comment by tdtds** [comment]
このissue、延々とmilestoneを延期し続けているだけなので、いったんmilestoreを外しました。仕切りなおすならいったんcloseするなりしましょう。

**Comment by machu** [comment]
v4.0.4で実装されているので、いったんクローズします。
https://github.com/tdiary/tdiary-core/releases/tag/v4.0.4
