### ISSUE TITLE
動的コンテンツをキャッシュに対応させたい

### ISSUE THREAD

**Issue by machu** [tdiary/tdiary-core#246]
tDiaryのコンテンツはRack環境でおおむね100msecのオーダー (200〜600msec) でコンテンツを返している。NginxなどのフロントWebサーバにてコンテンツをキャッシュすることで、10msecのオーダーでコンテンツを返すことが可能になる（約10倍の高速化）。

最近のtDiaryは動的コンテンツをクライアントサイドに追い出しているので、キャッシュの影響は小さくなっている。

注意事項としては…
- キャッシュの制御 … 日記を更新するとキャッシュを全クリア？
- ユーザエージェントにより返すコンテンツが違う（携帯、PC）
- 静的・動的コンテンツの区別 … 静的コンテンツは public 以下に置く

くらいでしょうかね。

参考
- http://www.hsbt.org/diary/20100426.html#p01
- http://www.hsbt.org/diary/20100427.html#p01
- http://www.hsbt.org/diary/20110127.html#p01

**Comment by tdtds** [comment]
このissueはmilestoneを延期してるだけなのでいったん外しました

**Comment by machu** [comment]
Webサーバ側で対応する問題なのでこちらはクローズします。
