### ISSUE TITLE
JavaScriptのロード回数を減らしたい

### ISSUE THREAD

**Issue by machu** [tdiary/tdiary-core#251]
プラグインのJavaScript化によってtDiary本体が軽くなる一方、.jsファイルのロード回数が増えている。RailsのようにJavaScriptを事前にマージして、ロード回数を減らしたい。

 * Sprocketsでできる？
 * 非Rack環境の考慮
 * プラグインの使用有無や `@mode` で呼び出すべき.jsファイルが変わることへの考慮

**Comment by tdtds** [comment]
このissueはmilestoneを延期してるだけなのでいったん外しました

**Comment by machu** [comment]
HTTP/2時代になってスクリプトファイルをマージするメリットがなくなったので、このissueと #381  のプルリクを閉じます。JavaScript読み込みの最適化は #568 にて。
