### ISSUE TITLE
tdiary newコマンドでPaaS向け環境を作成したい

### ISSUE THREAD

**Issue by machu** [tdiary/tdiary-core#305]
```
tdiary new --type=heroku
tdiary new --type=sqale
```

のように指定すると、PaaS環境向けのGemfileとtdiary.confをコピーする。

**Comment by tdtds** [comment]
このissueはmilestoneを延期してるだけなのでいったん外しました

**Comment by hsbt** [comment]
github の heroku デプロイボタンを押した、と同等の機能を提供できればいいのかなあ。heroku gem を integrate してコマンドを実行するようにすれば容易にできそう

**Comment by tdtds** [comment]
というかheroku buttonがあるいま、このissueにニーズはあるのか? (tDiary.NetではRakefileで同等機能を実現してるけど……)

**Comment by machu** [comment]
確かにもう不要ですね。クローズしちゃいます。
