### ISSUE TITLE
リンク元の記録を外部サービスに任せる

### ISSUE THREAD

**Issue by machu** [tdiary/tdiary-core#323]
tDiaryでリンク元の記録が重いという話があるので、Treasure Dataのような外部サービスに任せてしまいたい。プラグインで実現する。

**Comment by machu** [comment]
mongodbなど新しいioはそもそもリンク元を記録しないし、analyticsを使えばアクセス元も解析できるようになったので、tDiary側で対応する必要はなさそう。
https://github.com/tdiary/tdiary-io-mongodb

**Comment by tdtds** [comment]
移行パスというか、なんらかの代替手段は提示できたらいいかなぁとは思ってます。
