### ISSUE TITLE
2.0.0p291 で wiki_style を使うと SecurityError が起きる

### ISSUE THREAD

**Issue by hsbt** [tdiary/tdiary-core#360]
https://github.com/tdiary/tdiary-core/blob/master/tdiary/style/wiki_style.rb#L76

実行時に InsecureOperation - eval がおきます。2.0.0 でセキュリティモデル何か変わりましたっけ...

/cc @nagachika

**Comment by machu** [comment]
2年経つので一旦クローズしましょうか。

**Comment by tdtds** [comment]
ではそのように。
