### ISSUE TITLE
ドキュメントの提供形式を変える

### ISSUE THREAD

**Issue by hsbt** [tdiary/tdiary-core#390]
今は tdiary.org に置くために html にしてるけど、配布する時は md でもいいかもしれない。

**Comment by machu** [comment]
いまさらながら、どこのドキュメントでしたっけ？（doc内はmdになっていたので）

**Comment by tdtds** [comment]
tar.gz 内の doc 配下に md→html したものが入っていることですね。現状、配布物には md も残っているから、ここは close しちゃってもいいのかな。

**Comment by machu** [comment]
クローズしちゃいましょう。必要になればreopenする感じで。
