### ISSUE TITLE
tdiary.org を heroku に持っていく

### ISSUE THREAD

**Issue by hsbt** [tdiary/tdiary-core#396]
tdiary-chef や puppet とか色々やっていますが、www は heroku でいいんじゃないかと思いますがどうでしょうか。

MX レコード(あるの?) とパッケージ配布をどうしようかという懸念はありますが、パッケージは download.tdiary.net などを新しく割り当てて、今の www.tdiary.net のサーバーに置く or s3 当たりから配信するが良さそうな気がします。

**Comment by machu** [comment]
揮発性プラグインの問題はほぼ解決したと思いますが、Herokuの料金プランが変わったので改めて方針を決めましょうか。

 * Herokuのhobbyプランを使う
 * KDDIのVPSへ移行する
 * 今の.orgを使い続ける

パッケージ配布/MXとtdiary-blogkitは分けて運用しちゃっていいかなぁと。

**Comment by tdtds** [comment]
おお、すっかり忘れていました。しかし、Herokuはなかなかプラン強制移行を始めませんねぇ(笑)。 

@machu が動かしてるDocker環境ってもう安定してる感じです? KDDIホストでDocker運用というのが持続性という面で悪くないかなぁとも思うんですが。メモリは2GBあります。

**Comment by machu** [comment]
docker自体は安定して動いてます。稀にrpaproxyが落ちてますが、tdiaryは定常運転です。
メモリはdockerデーモンのオーバーヘッドがほとんどないので、2GBもあれば余裕でしょうね。うちはメモリ2GBでtdiaryとrpaproxyとpukiwikiと、フロントにnginxを動かしていて1.5GBくらい消費してます。

**Comment by machu** [comment]
パッケージ版の配布はgithubのrelease機能を使うのが良さそうです。試しに2つほど置いてみました。

https://github.com/tdiary/tdiary-core/releases

**Comment by machu** [comment]
とりあえずtdiary.orgのdockerイメージ作ってみますね。

**Comment by tdtds** [comment]
GitHubのreleaseって、リポジトリの特定タグを自動で固めたものだと思い込んでたw 独自のパッケージファイルを置けるなら、配布先はこれでいいですね。だったらサイトはDockerじゃなくても、Herokuで問題ない気もしますねぇ。

**Comment by machu** [comment]
Herokuで立ち上げてみます。

 * https://github.com/tdiary/tdiary-org
 * https://tdiary-org.herokuapp.com/

**Comment by tdtds** [comment]
Blogkitをgem化しないとダメかな

**Comment by machu** [comment]
ですね。 tdiary/tdiary-org#1 でissue上げました。

**Comment by machu** [comment]
tdiary-mongodb-convertを使ってblogデータをインポートしました。おおむね見えていますが、BlogKit固有プラグインの揮発性対応が必要ですね。

**Comment by machu** [comment]
続きは tdiary/tdiary-org#15 で。
