### ISSUE TITLE
EUC-JPのクエリパラメータを送るとプロセスが落ちる

### ISSUE THREAD

**Issue by shugo** [tdiary/tdiary-core#402]
unicornで運用しているのですが、例えば、 http://localhost:19292/?category=%A5%BD%A5%D5%A5%C8%A5%A6%A5%A7%A5%A2 (EUC-JPで「ソフトウェア])のようなEUC-JPのクエリパラメータを送ると、以下のようにプロセスが落ちてしまうようです。

      /home/shugo/.rbenv/versions/trunk/lib/ruby/2.2.0/cgi/core.rb:676:in `block (2 levels) in initialize_query': Accept-Charset encoding error (CGI::InvalidEncoding)
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/2.2.0/cgi/core.rb:671:in `each'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/2.2.0/cgi/core.rb:671:in `block in initialize_query'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/2.2.0/cgi/core.rb:670:in `each'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/2.2.0/cgi/core.rb:670:in `initialize_query'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/2.2.0/cgi/core.rb:828:in `initialize'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/bundler/gems/tdiary-core-948280841cdd/tdiary/dispatcher.rb:21:in `new'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/bundler/gems/tdiary-core-948280841cdd/tdiary/dispatcher.rb:21:in `call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/bundler/gems/tdiary-core-948280841cdd/tdiary/rack/valid_request_path.rb:17:in `block in call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/bundler/gems/tdiary-core-948280841cdd/tdiary/rack/valid_request_path.rb:16:in `each'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/bundler/gems/tdiary-core-948280841cdd/tdiary/rack/valid_request_path.rb:16:in `call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/bundler/gems/tdiary-core-948280841cdd/tdiary/rack/static.rb:15:in `call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/bundler/gems/tdiary-core-948280841cdd/tdiary/rack/html_anchor.rb:20:in `call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/bundler/gems/tdiary-core-948280841cdd/tdiary/application.rb:40:in `call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/reloader.rb:44:in `call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/lint.rb:49:in `_call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/lint.rb:37:in `call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/showexceptions.rb:24:in `call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/chunked.rb:43:in `call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/unicorn-4.8.0/lib/unicorn/http_server.rb:571:in `process_client'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/unicorn-4.8.0/lib/unicorn/http_server.rb:658:in `worker_loop'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/unicorn-4.8.0/lib/unicorn/http_server.rb:520:in `spawn_missing_workers'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/unicorn-4.8.0/lib/unicorn/http_server.rb:140:in `start'
      	from /home/shugo/.rbenv/versions/trunk/lib/ruby/gems/2.2.0/gems/unicorn-4.8.0/bin/unicorn:126:in `<top (required)>'
      	from /home/shugo/.rbenv/versions/trunk/bin/unicorn:23:in `load'
      	from /home/shugo/.rbenv/versions/trunk/bin/unicorn:23:in `<main>'
      E, [2014-01-27T10:56:00.597312 #22740] ERROR -- : reaped #<Process::Status: pid 22742 exit 1> worker=1
      I, [2014-01-27T10:56:00.597800 #22740]  INFO -- : worker=1 spawning...
      I, [2014-01-27T10:56:00.604131 #22747]  INFO -- : worker=1 spawned pid=22747
      I, [2014-01-27T10:56:00.607116 #22747]  INFO -- : worker=1 ready

手元ではTDiary::Application#callを以下のように修正して凌いでいますが、どうするのがよいでしょうか？

                def call( env )
                        @app.call( env )
                rescue Exception => e
                        $stderr.puts "#{e.class}: #{e.to_s}"
                        $stderr.puts e.backtrace
                        res = TDiary::Response.new
                        res.status = 500
                        res["Content-Type"] = "text/plain"
                        res.body = [e.to_s]
                        res.finish
                end

**Comment by tdtds** [comment]
上記PRを取り込んだのでcloseします。
