### ISSUE TITLE
Deploy to HerokuボタンでtDiaryを1クリックで設置できるようにしたい

### ISSUE THREAD

**Issue by machu** [tdiary/tdiary-core#462]
ボタンをクリックするだけでいい感じにHeroku上にセットアップしてくれるようにしたい。
[Introducing Heroku Button](https://blog.heroku.com/archives/2014/8/7/heroku-button)

**Comment by tdtds** [comment]
herokuブランチに必要な情報をセットして、Herokuボタンから利用可能にしました。tDiary.Netの知見を活かして、ストレージや認証まわりを決めてあります。
