### ISSUE TITLE
unicornでworker_processesが2以上だとomniauthに失敗する

### ISSUE THREAD

**Issue by Nyoho** [tdiary/tdiary-core#470]
unicorn で rack アプリとして tDiary を動かし、認証に omniauth を使うようにしようとすると
worker_processes が2以上のときに `OmniAuth::NoSessionError at /auth/twitter/callback` (Session Expired) で認証が失敗します。

> /Users/nyoho/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/omniauth-oauth-1.0.1/lib/omniauth/strategies/oauth.rb: in callback_phase
>         raise OmniAuth::NoSessionError.new("Session Expired") if session['oauth'].nil?...

worker_processes が 1 ですと正常に認証に成功します。また、bundle exec tdiary server や bundle exec rackup したときは同じ config.ru で問題なく認証されます。

上記の失敗する unicorn + worker processes >= 2 場合は、手元でテストプロジェクトを作って実験すると
TDiary::Rack::Auth::OmniAuth::CallbackHandler の call
https://github.com/tdiary/tdiary-core/blob/master/lib%2Ftdiary%2Frack%2Fauth%2Fomniauth.rb#L37
を通っていないようでした。
なぜなのかについてはまだよくわかりません。

**Comment by machu** [comment]
omniauth.rbでは、セッション管理にオンメモリの `Rack::Session::Pool` を使っています。
  https://github.com/tdiary/tdiary-core/blob/master/lib/tdiary/application/extensions/omniauth.rb#L7
プロセスが2つ以上の場合はセッション情報が共有されないので、認証に失敗しているようですね。

代替策として、複数プロセスでもセッションを共有できる `Rack::Session::Cookie` や `Rack::Session::Memcache` を使うと動きそうです。 `Rack::Session::Cookie` を使う場合は secret が漏れないように運用する必要があります。

**Comment by Nyoho** [comment]
なるほど、原因についてもよくわかりました。解説いただきありがとうございました!
Memcacheを使う方法などを検討してみます。

**Comment by machu** [comment]
環境によってセッションの実装が変わるので、omniauth.rbでuseするよりも、config.ruで指定するほうが使いやすそうですね。

**Comment by Nyoho** [comment]
そうですね。今手元で `Rack::Session::Dalli` で memcached を使う方法で動くことを確認しましたが、
tdiary.conf の @options['use_dalli'] のようなことを入れたらいいかと思っていました。
おっしゃる通り config.ru で `Rack::Session` に何を使うか切り替えた方がスマートですね。

**Comment by machu** [comment]
tdiary.confはTDiaryApplication (正確にはその先で呼ばれるDispatcher::UpdateMain) の実行後に読み込まれるので、Rack層の設定には使えないんですよね。
Rackサーバーの設定はconfig.ru、tDiary本体の設定はtdiary.confという使い分けになってます。config.ruの一部をextentionに持っていったせいで、少し複雑になってますが。

**Comment by Nyoho** [comment]
なるほど! ありがとうございます。
Rack層の設定だけなので tDiary gem のコードをいじる必要がなく(いじるべきではなく)、config.ru で対応できると。
うまく役割が分かれていて素晴らしいですね。 

ひとまず `tdiary/application/extensions/omniauth` をがばっと config.ru にコピペして、`use Rack::Session::Dalli` するようにしただけで、複数 workers の unicorn で認証が成功し続けました。

**Comment by tdtds** [comment]
Dalliが入っていると自動的にセッション情報をmemcacheに入れるようにしました、というご報告。
https://github.com/tdiary/tdiary-core/pull/484

**Comment by Nyoho** [comment]
:+1: これはありがとうございます!
より config.ru をシンプルにできて助かります。
