### ISSUE TITLE
揮発性のPaaS環境でフィードを出力できるようにする

### ISSUE THREAD

**Issue by machu** [tdiary/tdiary-core#472]
Herokuのような揮発性の環境では、makerssプラグインでフィードを出力しても、サーバプロセスが停止するタイミングでフィードが消えてしまう。
フィードをファイルとして出力するのではなく、アプリ側で返すようにする。
tDiaryはカテゴリプラグインのようにHTMLを出力する前提の設計となっているので、XMLを動的に出力する仕組みが必要。

**Comment by tdtds** [comment]
この問題は以前から考えていたんですが、動的生成もひとつの手ですがちょっと実装が大掛かりなのと処理が重いので、最初の起動時に静的ファイルを再生成するアイデアはどうかなと思っています。

**Comment by machu** [comment]
なるほど。add_header_procあたりでindex.rdfの存在チェックをすれば、簡単に実装できそうですね。
一方、インスタンス停止状態でフィードにアクセスされると404になってしまうので、も少し考えてみます。

**Comment by tdtds** [comment]
header_procだといきなり静的ファイルにアクセスがあった場合に404になってしまうので、「最初の起動時」つまりプロセスがあがったタイミングになにか動かせる口を作らないとダメだと思う。さすがにそこは新しいI/Fが必要かな。

(インスタンス停止状態ではアクセスをさばくことはないのでそもそも404にすらならないのでは?)

**Comment by machu** [comment]
あ、なるほど。いまだと、Rack::Staticに到達するまでに動けばいいですね。

**Comment by tdtds** [comment]
#474 にて実装。
