### ISSUE TITLE
rake assets:copyの出力先が public/assets ではなく lib/public/assets になっている

### ISSUE THREAD

**Issue by tamoot** [tdiary/tdiary-core#475]
lib/tdiary/tasks/assets.rake の相対パスに対応が必要です。

```Ruby
   task :copy do
      require 'fileutils'
      # -> lib/public/assetsになってしまう
      # assets_path = File.dirname(__FILE__) + '/../../public/assets'
      # 期待は public/assets ですよね
      assets_path = File.dirname(__FILE__) + '/../../../public/assets'
      FileUtils.mkdir_p assets_path

```

**Comment by machu** [comment]
#432 での変更漏れですね。ありがとうございます。
ちなみに今なら `bundle exec rake assets:copy` よりも `bundle exec bin/tdiary assets_copy` のほうが便利です。 tdiary-contribをgemでインストールしている場合に、contribで使うjsファイルもコピーしてくれます。

と書きつつ、 `bundle exec bin/tdiary assets_copy` も動かなくなっていたので、 #477 で直しました。

**Comment by tdtds** [comment]
これ閉じていいかな? というか閉じますね。

**Comment by tamoot** [comment]
ありがとうございました！(ステータス見落としてました。。。
