### ISSUE TITLE
カテゴリプラグインが生成するURLにアクセスした際の表示が異なっている(と思います・・自信なし

### ISSUE THREAD

**Issue by tamoot** [tdiary/tdiary-core#485]
最新版 + rack + puma環境です。

カテゴリプラグインの ``表示期間の初期状態``

```
カテゴリ表示画面を表示した時の、最初の表示期間を指定します。 
```

を四半期に設定したあと、category_to_tagプラグインの生成するパラメータが以下となりました。

```
http://www.tamoot.net/d/?year=2015;month=1Q;category=Ruby
```

上記にアクセスすると日記トップページが表示されました。

以下のように ``category=Ruby`` を前にもってくると、指定した表示期間かつカテゴリの表示となりました。

```
http://www.tamoot.net/d/?category=Ruby;year=2015;month=1Q
```

古いtDiaryやcgi環境だと変わるのかどうか、後で確認してみます。

**Comment by tdtds** [comment]
報告された状況はこちらでも確認しました。categoryパラメタを最初に持ってくるのがポイントではなくて、パラメタ区切りを「;」から「&」に変えるとちゃんと期待したとおりの動作をしますね。

`dispatcher/index_main.rb`ではそういう誤動作をする振り分けをしていないので、Rackから渡ってくるresuestが「;」区切りに対応してないのかな。さて、どうしたものか。

**Comment by Nyoho** [comment]
ひょっとしたら rack が 1.6.0 で、
https://github.com/rack/rack/commit/71c69113f269f04207157bee6c197b5675f3df61#diff-345b5336fcb3ce47a50decd2176d79e8R331
を取り込んで、GETのときでも「;」をセパレータとしなくなってしまったことが原因でしょうか。

hiki を rack を使っていて気付いたメモです: hiki rack メモ - https://gist.github.com/Nyoho/6a20c0975cbeeecd6f9b
rack に pull request を出したみたものを、メモにコメントで追記しておきましたが、実際にどうなおすのがよいか、まだ僕はわかっていません。

**Comment by tdtds** [comment]
W3Cのご威光まで含めてのPR、GJだと思います :+1: 

常識的に考えれば取り込まれると思うので、tDiary的にはrackのバージョンを1.6未満に指定して様子をみる、という感じかなぁ。

**Comment by tdtds** [comment]
とりあえず`'~> 1.5.0'`としておきました。このissueはこのままopenしておきます。4.1.2リリース時に見直す感じで。

**Comment by hsbt** [comment]
> とりあえず'~> 1.5.0'としておきました。

:eyes: 了解です。

**Comment by tamoot** [comment]
bundle install して rack1.5.2がインストールされた後で期待通りの動作となることを確認できました。

http://www.tamoot.net/d/?year=2015;month=1Q;category=tDiary

**Comment by machu** [comment]
3/23時点ではまだRackへのPRはまだオープン状態。

https://github.com/rack/rack/pull/781

**Comment by tdtds** [comment]
応援しといた

**Comment by Nyoho** [comment]
応援いただき、ありがとうございます!
さてさてrack側がどう解決されるのか……

**Comment by tamoot** [comment]
rack/rack#781 がクローズされたので、 試してみました。四半期表示も問題ありませんでした。

**Comment by tdtds** [comment]
あ、最新のrack gemにこれ入ってるのかな?

**Comment by tamoot** [comment]
しまった、、、勘違いしてましたorz 1.6.1に入ってない様子です。

**Comment by machu** [comment]
rack 1.6.3で取り込まれました。tDiaryでも新しいrackを使うようにします。
https://github.com/rack/rack/commit/a853058100191edabac5d73c9713aa5d0dce5530
