### ISSUE TITLE
Gemfile.localに書くだけでOmniAuth認証を自動で有効にする

### ISSUE THREAD

**Issue by machu** [tdiary/tdiary-core#486]
今はconfig.ruで明示的にomniauthのextension をrequireしている。
Gemfile.localにomniauthを指定するだけで、自動的にOmniAuth認証が有効になるようにする。
heroku用のconfig.ruと本体のconfig.ruも一本化できる。

**Comment by tdtds** [comment]
:+1:

**Comment by machu** [comment]
#490 で対応した。合わせて、FacebookやGoogle認証もサポートするようになった。
