### ISSUE TITLE
omniauthで認証に失敗する

### ISSUE THREAD

**Issue by kp1** [tdiary/tdiary-core#494]
tDiary4.1.2でomniauthを試してみたところ、認証に失敗してリダイレクトループが発生しています。

Gemfile.local
 gem 'tdiary-contrib', :path => '/home/kp/workspace/tdiary-contrib'
 gem 'market_bot','0.12.1'
 gem 'exifparser'
 gem 'omniauth'
 gem 'omniauth-github'
 gem 'unicorn'

こちらの環境が悪いような気もしていますが、
どこから見ればいいかわからない状態です。

**Comment by kp1** [comment]
thinでログをとったら以下のような感じでした。

127.0.0.1 - - [09/Apr/2015 22:47:22] "GET /diary/update.rb/auth/github HTTP/1.0" 302 245 0.0169
I, [2015-04-09T22:47:23.033632 #28536]  INFO -- omniauth: (github) Callback phase initiated.
E, [2015-04-09T22:47:23.034227 #28536] ERROR -- omniauth: (github) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected
E, [2015-04-09T22:47:23.034395 #28536] ERROR -- omniauth: (github) Authentication failure! invalid_credentials: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected

nginxの設定かも…

**Comment by machu** [comment]
GitHubのログイン画面までは出るのですよね。omniauthはログイン画面の前（requestフェーズ）とログイン画面の後（callbackフェーズ）でセッション情報を使って情報を受け渡ししているのですが、それがうまく取れていないのかもしれません。
unicornのエラーログにomniauth系のメッセージが出ていたりしますでしょうか？

**Comment by machu** [comment]
あ、すれ違いました。

**Comment by kp1** [comment]
試しにomniauth-oauth2で、provider_ignores_stateをtrueにしたところ、CSRF detectedは回避できましたがbase_dirにリダイレクトされました。ということでSession:Poolでセッションが保持できていない状態のようでした。

#470 を参考にmemcached,dalliを導入したところ、provider_ignores_state=falseでも問題なく認証できました。

**Comment by machu** [comment]
なるほど。セッションに保存しているデータがSession::Poolに入りきれていないのかもしれません。うーん。

**Comment by machu** [comment]
時間がかかりましたが、ようやく原因が特定できました。
