### ISSUE TITLE
http://docs.tdiary.org/ja/ にスパムが多いようです

### ISSUE THREAD

**Issue by tamoot** [tdiary/tdiary-core#504]
先程スパムページを13個ほど削除しました。

いたちごっこの様相なので、以下のどれかを検討したほうがよいのでは、と考えました。
1. 代替のwikiを探す
2. github.ioあたりで公開する (wikiと比較して敷居が上がる？
3. プラグインの使い方は、docs.tdiary.orgにリンクではなく、docへ記事を取り込んでしまう、等・・・

いかがでしょうか。

**Comment by tdtds** [comment]
そうですねー、あの簡単な認証はもう通用しないってことなんですよねぇ。

持続性とメンテナンス性から考えると、markdown化してGitHubのWikiに入れちゃうのがいいのかなと思いますが……。

**Comment by hsbt** [comment]
github pages にしてドメイン割り当てるとかですかねえ...

**Comment by tdtds** [comment]
要件としてはこんな感じかな:

* 自前でサーバ維持とかしたくない。プロジェクトが存続するかぎりほっといても提供し続けられると良い
* 完全匿名は(対spam的に)無理なのでなんらかの認証は必要だが、できるだけ敷居は低く保ちたい
* マークアップ言語は(移行の手間を考えると)HikiDocがベストだが、普及率を考慮してMarkdownでも可

**Comment by tamoot** [comment]
githubを生かす案を考えてみました。githubのアカウントが必要になる点は敷居の高低判断が難しいですね。

1. ```tDiary-Wiki organization``` を新設して、wikiだけ運営
2. wikiを更新する人は ```tDiary-Wiki organization``` に入ってもらう

**Comment by tdtds** [comment]
GitHubは最後の手段かなぁと感じてます(UIが英語のみなので)。

とはいえ、Wikiを更新する(すべき)人は主に開発者ではあるので、コードを書ける人とWikiを編集できる人はかなり重なっていると考えるのはありかも知れません。だとすれば英語はたいしたハードルではない。

あと、わざわざorganizationを起こさなくても、tDiary organizationにdocument teamでも作ればいいように思いますね(contrib teamと同じ運用)。

**Comment by tdtds** [comment]
docs.tdiary.orgのメンテがつらい感じになってきたようなので、この案件、進めましょう。GitHubのtDiary organizationにdocumentリポジトリを作って、そこのWikiに移設する方向で。

**Comment by machu** [comment]
今ごろ気がついたけど、Hikiでサポートされている定義リストがMarkdownでは使えない。

**Comment by tamoot** [comment]
ちょっとだけ書いてみました。こんな具合でどうでしょうか。

https://github.com/tamoot/tdiary-document/blob/master/README.md

**Comment by tdtds** [comment]
「こんな具合」というのが文書形式のことであれば、こんな感じで良いと思います。定義リストはまぁ、なくてもなんとかなりますよね。
格納形式のことであれば、リポジトリではなくWikiでやるべきだと思います。
いずれにせよ、ぼちぼち重い腰をあげないといけませんね(^^;

**Comment by tamoot** [comment]
そうですね、wikiが良いですね。（普段の癖でリポジトリで作ってしまいました。）

1. `tdiary/tdiary-document` プロジェクト作成
2. tdiary organizaition に `document team` を作成
3. 2のメンバーは1のwikiアクセス可とする
4. せっせと移植

**Comment by tdtds** [comment]
「せっせと移植」の部分、できれば:

4.1 元データ(Wikiスタイル)を入手
4.2 Markdownに自動変換
4.3 微調整

にできるといいなぁ……。Wikiの生データって、まとめて入手できたりします? > @fdiary

**Comment by fdiary** [comment]
MySQLにあるので、まとめて入手できるけれど、ちょっと時間をください。

お急ぎなら、 http://docs.tdiary.org/ja/?c=index をスクレイピングして一覧をとって、それぞれソースのURLをクロールして持っていってくれてもいいです。  😃

**Comment by tdtds** [comment]
@fdiary じゃあしばらくは待ってみます、ありがとう！

**Comment by tdtds** [comment]
いろいろ移行作業を始めようと思うので、まずは [tdiary-documentリポジトリ](https://github.com/tdiary/tdiary-document)と、Documentチームを作成した。Documentチームに入りたい人は、[向こうの当該Issue](https://github.com/tdiary/tdiary-document/issues/1)にコメントで申請してね。

**Comment by tdtds** [comment]
既存のドキュメントをGitHub Wikiに移転、明後日リリース予定の5.0.7からはそちらを参照するようにリンクを張り替えました。過去のバージョンからはまだdocs.tdiary.orgを参照しているので旧Wikiはまだ残しますが(いずれリダイレクトさせたい)、とりあえずこのissueは閉じますね。
