### ISSUE TITLE
ruby 2.3のサポート

### ISSUE THREAD

**Issue by machu** [tdiary/tdiary-core#513]
ruby-2.3.0が2015/12/25にリリースされます。tDiaryのリリースが12/29なので、次リリースでサポートに追加しましょう。

 * [Ruby 2.3.0-preview1 リリース](https://www.ruby-lang.org/ja/news/2015/11/11/ruby-2-3-0-preview1-released/)
 * [ReleaseEngineering23](https://bugs.ruby-lang.org/projects/ruby-trunk/wiki/ReleaseEngineering23)

**Comment by tdtds** [comment]
そうですね。CIは常にheadでも走ってるから、リリースタイミングで2.3を加えればいい感じかな? 同梱するパッケージの2.3.0ディレクトリの追加を忘れないようにしないとか。

**Comment by machu** [comment]
ruby2.3.0がリリースされたので、tDiary側でも対応しました。
