### ISSUE TITLE
jQuery 1.9.xへのアップデート

### ISSUE THREAD

**Issue by kp1** [tdiary/tdiary-core#523]
bootstrap.js を使用したいので、可能であればjQuery 1.9.1以降にアップデートしてほしいです。

**Comment by tdtds** [comment]
どうせならと思って最新版に差し替えたPRを作りましたが(#525)、このタイミングで入れるのはちょっと怖いかな……。依存するライブラリのメンテナに意見を聞きたいところ。

もしbootstrapを使う理由がレスポンシブデザインのためだとしたら、今後はそういうライブラリには頼らず、CSS3のflexboxを使うのがスジが良いと考えています。今後coreやthemeでサポートをしていくとしたらそっちの方向にしたいです。

**Comment by kp1** [comment]
まさに、その通りの動機ですがbootstrapは重いですね。
flexbox勉強します。

**Comment by machu** [comment]
query2はIE8に未対応なので、いまは1系の最新を使っておいて、html5対応と合わせてjquery2へ移行するのがいいかなと思います。

ここ数日bootstrap3を使ってみましたが、tdiary本体に入れてしまうとテーマデザインの制約が大きくなりそうです。tdiary本体では素のHTML5 + CSS3を使うようにして、テーマの1つとしてbootstrapを使うのはアリだと思います。

**Comment by tdtds** [comment]
じゃあIE8は来年1月にサポートが切れるから(cf. [ipa.go.jp](https://www.ipa.go.jp/security/ciadr/vul/20151215-IEsupport.html))、#525 は3月のリリースに入れましょうか。

**Comment by tamoot** [comment]
category_autocomplete, comment_emoji_autocomplete共に動作しました！
