### ISSUE TITLE
herokuでのbuildに失敗する

### ISSUE THREAD

**Issue by machu** [tdiary/tdiary-core#527]
herokuブランチを最新のmasterに追従させようとしたところ、herokuでのbuild中にフリーズするようになりました。`Cleaning up the bundler cache`の途中で応答が返ってこなくなります。

```
$ git push heroku heroku:master
Counting objects: 5, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 456 bytes | 0 bytes/s, done.
Total 5 (delta 2), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rack
remote: -----> Using Ruby version: ruby-2.2.3
remote: -----> Installing dependencies using bundler 1.9.7
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Fetching gem metadata from https://rubygems.org/.......
remote:        Fetching version metadata from https://rubygems.org/...
remote:        Fetching dependency metadata from https://rubygems.org/..
remote:        Using rake 10.4.2
（中略）
remote:        Using tdiary 4.2.0.20151206 from source at .
remote:        Using tdiary-contrib 4.2.0 from git://github.com/tdiary/tdiary-contrib.git (at master)
remote:        Bundle complete! 24 Gemfile dependencies, 54 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Bundle completed (3.84s)
remote:        Cleaning up the bundler cache.
remote: ^C
```

正常な場合は、以下のように`Cleaning up the bundler cache`が続きます。

```
remote:        Bundle complete! 30 Gemfile dependencies, 52 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into ./vendor/bundle.
remote:        Bundle completed (2.55s)
remote:        Cleaning up the bundler cache.
remote:        Removing coffee-script (2.4.1)
remote:        Removing ref (2.0.0)
remote:        Removing concurrent-ruby (1.0.0)
remote:        Removing libv8-3.16.14.13-x86_64 (linux)
remote:        Removing mime-types (2.99)
remote:        Removing coffee-script-source (1.10.0)
remote:        Removing execjs (2.6.0)
remote:        Removing sprockets (3.5.2)
remote:        Removing therubyracer (0.12.2)
remote:        Removing fastimage (1.8.1)
```

**Comment by machu** [comment]
#517 のプルリクが原因のようなので、もう少し調べます。これをrevertしたら動くようになりました。

**Comment by tdtds** [comment]
うーん、ライブラリの作法をアプリに適用しちゃあかんかったのか……

**Comment by machu** [comment]
内部的には`bundle clean`を実行しているところで止まっています。buildpackを書き換えて他のコマンドを動かしてみたところ、`bundle show`や`rake`も動かなくなっているので、cleanが問題というよりbundle installの過程で環境が壊れているような気もします。

**Comment by machu** [comment]
いずれにせよherokuで動かないのは問題なので、リリース前に #517 はいったんrevertしますかねー。

**Comment by tdtds** [comment]
Heroku側の問題ってこと?

**Comment by machu** [comment]
はい。やってることはherokuもそれ以外も同じで、bundle installしているだけですので。

**Comment by tdtds** [comment]
そうか。じゃあとりあえずrevertしてください。あとはいちおう @zunda さんに知らせておこうw

**Comment by zunda** [comment]
はいっw [Gemfileの記法が新しすぎるのかなあ、などと](https://twitter.com/zundan/status/679259027801374720)なんとなくは思ってますが、どうやって確かめようかな。

**Comment by tdtds** [comment]
認識ずみだったのかw

**Comment by machu** [comment]
いま分かっていること。

 * 手元のMac環境ではbundler1.9.7でもビルドできました。
 * buildpackを修正し、bundle install以降の手順 (bundle cleanとrake) をスキップして無理やりdeployすることで、heroku run bashで対象dynoに接続できます。その環境ではbundle cleanも実行できました。

gemspecを使う最小構成を作って、再現するかどうか試してみようと思います。

**Comment by tdtds** [comment]
work aroundは #529 で対処できたので、このissueは残しつつ次のリリースに回します。

**Comment by tdtds** [comment]
これはもう解決しているように見えるんだけど、Closeしてもいいのかしらん? Milestoneは次に延ばしますが、問題ないならCloseしちゃってください。

**Comment by zunda** [comment]
[動かし方- Herokuの場合](https://github.com/tdiary/tdiary-core/blob/master/doc/INSTALL-paas.md#%E5%8B%95%E3%81%8B%E3%81%97%E6%96%B9---heroku-%E3%81%AE%E5%A0%B4%E5%90%88)に従ってデプロイできることを確認しました。

[heroku-buildpack-ruby](https://github.com/heroku/heroku-buildpack-ruby)の[master版を使っている](https://github.com/tdiary/tdiary-core/blob/master/app.json#L30)ので、[リリース版](https://devcenter.heroku.com/changelog-items/832)の[bundler 1.11.2](https://github.com/heroku/heroku-buildpack-ruby/blob/v146/lib/language_pack/ruby.rb#L17)よりも新しい[bundler 1.13.1](https://github.com/heroku/heroku-buildpack-ruby/blob/master/lib/language_pack/ruby.rb#L17)でデプロイが進みました。

```
  :
-----> Ruby app detected
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-2.3.1
-----> Installing dependencies using bundler 1.13.1
  :
       Bundle completed (23.07s)
       Cleaning up the bundler cache.
  :
```

というわけでHeroku側でのbundlerのバージョンの更新で問題は解決したように見えます。あとでリリース版のheroku-buildpack-rubyでどうなるか試してみますね。

**Comment by machu** [comment]
いまHerokuで動くのは #528 のwork aroundを入れてるからですね。tDiaryの依存ライブラリがGemfileとtdiary.gemspecの二ヶ所に書かれていてDRYじゃない状態です。
確認用のブランチ作りますね。

**Comment by tdtds** [comment]
よろしくですー

**Comment by machu** [comment]
確認用のブランチ #590 を作りましたが、ビルドに失敗する事象は直っていませんでした。当面は依存ライブラリを `Gemfile` と `tdiary.gemspec` の両方に書くようにします。

**Comment by machu** [comment]
> 当面は依存ライブラリを Gemfile と tdiary.gemspec の両方に書くようにします

という対処でいったんクローズします。
