### ISSUE TITLE
開発スナップショット版の更新が止まっている

### ISSUE THREAD

**Issue by machu** [tdiary/tdiary-core#536]
[tdiary.orgで配信されている](http://www.tdiary.org/20021112.html)開発スナップショット版が2014年から更新されてません。いまどきtar.gzでスナップショットを取得する人もいなさそうなので、いっそ止めてしまいましょうか。

**Comment by tdtds** [comment]
oh...たしかに。スナップショットの記述を削除して、Gitを使うように誘導しました。その他、現状に合わせて記述を変更。

**Comment by machu** [comment]
いいですね！ありがとうございます〜。
