### ISSUE TITLE
index.rb の rescue Exception で invalid byte sequence in UTF-8 (ArgumentError)

### ISSUE THREAD

**Issue by znz** [tdiary/tdiary-core#555]
wheezy から jessie にあげて、使う ruby も /usr/bin/ruby1.8 から /usr/bin/ruby (ruby 2.1.5) にあげたところ、 /usr/share/tdiary/index.rb で

```
/usr/lib/ruby/2.1.0/cgi/util.rb:37:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)
\tfrom /usr/lib/ruby/2.1.0/cgi/util.rb:37:in `escapeHTML'
\tfrom /usr/share/tdiary/index.rb:50:in `rescue in <top (required)>'
```

という例外が発生していたのが apache の error log に記録されていて、ブラウザー側のエラー表示は
「500 Internal Server Error」だけで切れていました。

2行目のマジックコメントを `# -*- coding: ascii-8bit; -*-` に変更したところ、ちゃんとバックトレースまでブラウザー上に表示されるようになったので、[index.rb のマジックコメント](https://github.com/tdiary/tdiary-core/blob/976ad5e9b795b059660015d6cabf727def00bfa5/index.rb#L2) は ascii-8bit にした方が良いのではないかと思うのですが、いかがでしょうか。

**Comment by tdtds** [comment]
なるほど、これは確かにそうですね。むしろマジコメのデフォルトがUTF-8になったからこそ、ASCII-8BITを指定しなければいけないのか。そのようにします。
