### ISSUE TITLE
cygwin環境でパッケージ版のtDiaryが起動しない

### ISSUE THREAD

**Issue by machu** [tdiary/tdiary-core#569]
sprocketsが依存している [concurrent-ruby](https://github.com/ruby-concurrency/concurrent-ruby) でエラーが出ている模様。

see: https://gist.github.com/mumriks/5e4b890950bfb1ca71264385bd0871b2

```
Ruby-2.3.1+tDiary-5.0.0
------
500 Internal Server Error

cannot load such file -- concurrent/synchronization/abstract_object (LoadError)

~/public_html/diary/.bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.1/lib/concurrent/synchronization.rb:3:in `require'
~/public_html/diary/.bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.1/lib/concurrent/synchronization.rb:3:in `<top (required)>'
~/public_html/diary/.bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.1/lib/concurrent/atomic/event.rb:2:in `require'
~/public_html/diary/.bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.1/lib/concurrent/atomic/event.rb:2:in `<top (required)>'
~/public_html/diary/.bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.1/lib/concurrent/concern/obligation.rb:4:in `require'
~/public_html/diary/.bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.1/lib/concurrent/concern/obligation.rb:4:in `<top (required)>'
~/public_html/diary/.bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.1/lib/concurrent/delay.rb:2:in `require'
~/public_html/diary/.bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.1/lib/concurrent/delay.rb:2:in `<top (required)>'
~/public_html/diary/.bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.1/lib/concurrent/configuration.rb:2:in `require'
~/public_html/diary/.bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.1/lib/concurrent/configuration.rb:2:in `<top (required)>'
~/public_html/diary/.bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.1/lib/concurrent.rb:4:in `require'
~/public_html/diary/.bundle/ruby/2.3.0/gems/concurrent-ruby-1.0.1/lib/concurrent.rb:4:in `<top (required)>'
~/public_html/diary/.bundle/ruby/2.3.0/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:4:in `require'
~/public_html/diary/.bundle/ruby/2.3.0/gems/sprockets-3.5.2/lib/sprockets/manifest.rb:4:in `<top (required)>'
~/public_html/diary/.bundle/ruby/2.3.0/gems/sprockets-3.5.2/lib/sprockets.rb:6:in `require'
~/public_html/diary/.bundle/ruby/2.3.0/gems/sprockets-3.5.2/lib/sprockets.rb:6:in `<top (required)>'
~/public_html/diary/misc/lib/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
~/public_html/diary/misc/lib/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
~/public_html/diary/misc/lib/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
~/public_html/diary/misc/lib/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
~/public_html/diary/misc/lib/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
~/public_html/diary/misc/lib/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
~/public_html/diary/misc/lib/bundler-1.11.2/lib/bundler.rb:99:in `require'
~/public_html/diary/lib/tdiary/environment.rb:20:in `<top (required)>'
~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
~/public_html/diary/lib/tdiary.rb:26:in `<top (required)>'
~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
~/public_html/diary/index.rb:18:in `<main>'
```

**Comment by machu** [comment]
CGI環境なので、そもそもRackでしか使わないsprocketsは不要なはず。

 * テキストエディタでGemfileを開き、 `gem 'sprockets'` の行を削除 （sprocketsライブラリを使わない）
 * コマンドラインで bundle コマンドを実行 （更新したGemfileの内容でライブラリの依存関係を更新）
 * CGI経由で日記にアクセス

とすると動くかもしれません > @mumriks

**Comment by mumriks** [comment]
Gemfile の gem 'sprockets' を削除して、bundle コマンドを実行したところ以下のようになりました。

$ bundle
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- molinillo (LoadError)
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/share/gems/gems/bundler-1.9.9/lib/bundler/vendored_molinillo.rb:5:in `<top (required)>'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/share/gems/gems/bundler-1.9.9/lib/bundler/resolver.rb:12:in `<class:Resolver>'
        from /usr/share/gems/gems/bundler-1.9.9/lib/bundler/resolver.rb:10:in `<module:Bundler>'
        from /usr/share/gems/gems/bundler-1.9.9/lib/bundler/resolver.rb:9:in `<top (required)>'
        from /usr/share/gems/gems/bundler-1.9.9/lib/bundler/definition.rb:192:in `resolve'
        from /usr/share/gems/gems/bundler-1.9.9/lib/bundler/definition.rb:158:in `missing_specs'
        from /usr/share/gems/gems/bundler-1.9.9/lib/bundler/installer.rb:70:in `block in run'
        from /usr/share/gems/gems/bundler-1.9.9/lib/bundler/ui/shell.rb:74:in `silence'
        from /usr/share/gems/gems/bundler-1.9.9/lib/bundler/installer.rb:67:in `run'
        from /usr/share/gems/gems/bundler-1.9.9/lib/bundler/installer.rb:18:in `install'
        from /usr/share/gems/gems/bundler-1.9.9/lib/bundler/cli/install.rb:80:in `run'
        from /usr/share/gems/gems/bundler-1.9.9/lib/bundler/cli.rb:155:in `install'
        from /usr/share/gems/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/share/gems/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/share/gems/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/share/gems/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/share/gems/gems/bundler-1.9.9/lib/bundler/cli.rb:10:in `start'
        from /usr/share/gems/gems/bundler-1.9.9/bin/bundle:20:in `block in <top (required)>'
        from /usr/share/gems/gems/bundler-1.9.9/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
        from /usr/share/gems/gems/bundler-1.9.9/bin/bundle:18:in `<top (required)>'
        from /usr/bin/bundle:23:in `load'
        from /usr/bin/bundle:23:in `<main>'

ためしに gem install molinillo とすると、cannot load such file -- win32/resolv (LoadError) になりました。

**Comment by machu** [comment]
なるほど。bundleもgem installも使えない環境なのですね。
パッケージ版から本来不要なsprocketsを取り除いてみました。
何度もすみません、これでどうでしょうか > @mumriks

[tdiary-snapshot.tar.gz](https://github.com/tdiary/tdiary-core/files/261936/tdiary-snapshot.tar.gz)

**Comment by mumriks** [comment]
失礼しました。bundle は使えています。addressable ほか 10 の gem がインストールはされたようです。
sprockets を除いていただいた snapshot を試したところ、今度は以下のようなエラーが表示されました。

==========
500 Internal Server Error

cannot load such file -- thor/core_ext/hash_with_indifferent_access (LoadError)

~/public_html/diary/.bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:2:in `require'
~/public_html/diary/.bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:2:in `<top (required)>'
~/public_html/diary/.bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:2:in `require'
~/public_html/diary/.bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:2:in `<top (required)>'
~/public_html/diary/.bundle/ruby/2.3.0/gems/emot-0.0.4/lib/emot/cli.rb:1:in `require'
~/public_html/diary/.bundle/ruby/2.3.0/gems/emot-0.0.4/lib/emot/cli.rb:1:in `<top (required)>'
~/public_html/diary/.bundle/ruby/2.3.0/gems/emot-0.0.4/lib/emot.rb:4:in `require'
~/public_html/diary/.bundle/ruby/2.3.0/gems/emot-0.0.4/lib/emot.rb:4:in `<top (required)>'
~/public_html/diary/misc/lib/bundler-1.12.1/lib/bundler/runtime.rb:86:in `require'
~/public_html/diary/misc/lib/bundler-1.12.1/lib/bundler/runtime.rb:86:in `block (2 levels) in require'
~/public_html/diary/misc/lib/bundler-1.12.1/lib/bundler/runtime.rb:81:in `each'
~/public_html/diary/misc/lib/bundler-1.12.1/lib/bundler/runtime.rb:81:in `block in require'
~/public_html/diary/misc/lib/bundler-1.12.1/lib/bundler/runtime.rb:70:in `each'
~/public_html/diary/misc/lib/bundler-1.12.1/lib/bundler/runtime.rb:70:in `require'
~/public_html/diary/misc/lib/bundler-1.12.1/lib/bundler.rb:102:in `require'
~/public_html/diary/lib/tdiary/environment.rb:18:in `<top (required)>'
~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
~/public_html/diary/lib/tdiary.rb:25:in `<top (required)>'
~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
~/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
~/public_html/diary/index.rb:18:in `<main>'
==========
gem install は確かにうまく機能していないみたいです。なにをインストールしようとしても win32/resolv (LoadError) になりますね。

**Comment by mumriks** [comment]
thor/core_ext/hash_with_indifferent_access ですが、

~/public_html/diary/.bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/core_ext にはありませんが、

~/public_html/diary/.bundle/ruby/gems/thor-0.19.1/lib/thor/core_ext には存在します。

snapshot の時点では後者のパスが存在していないので、bundle を実行してインストールされたのは
後者側かと思われますが、実行時には前者のパスを見に行ってファイルがないという結果になっているということでしょうか。

ということで、thor/core_ext/hash_with_indifferent_access を /2.3.0/gems/thor-0.19.1/lib/thor/core_ext/ にコピーしたところ少し進み、今度は、

cannot load such file -- mail/fields/content_transfer_encoding_field (LoadError)

とのことだったのでこちらも同様にコピーしてみると、

no implicit conversion of nil into String (TypeError)

~/public_html/diary/lib/tdiary/dispatcher/index_main.rb:38:in `digest'
~/public_html/diary/lib/tdiary/dispatcher/index_main.rb:38:in `hexdigest'
~/public_html/diary/lib/tdiary/dispatcher/index_main.rb:38:in `run'
~/public_html/diary/lib/tdiary/dispatcher/index_main.rb:5:in `run'
~/public_html/diary/lib/tdiary/dispatcher.rb:25:in `dispatch_cgi'
~/public_html/diary/index.rb:32:in `<main>'

というところまでたどりつきました。

**Comment by machu** [comment]
index_main.rbの38行目でそのエラーということは、bodyがnilになっているということですね。bodyはERB.resultの戻り値が入っているので、nilになるのが謎だ…。

```ruby
body = tdiary.eval_rhtml
head['ETag'] = %Q["#{Digest::MD5.hexdigest( body )}"]
```

https://github.com/tdiary/tdiary-core/blob/d919a2fd0ad292269f62d16be2ccd75c3620b27e/lib/tdiary/dispatcher/index_main.rb#L38

**Comment by mumriks** [comment]
どうもパッケージの展開に失敗していたらしく、いくつかのファイルがなかったり、おかしな状態になっていたりしたものがあったようです。
展開しなおして比較してみてわかりました。
逐一確認しつつすすめたところ、データのないまっさらな状況では Ruby-2.3.1 と  tDiary-5.0.0 が動作することを確認できました。
[http://mumrik.air-nifty.com/blog/2016/05/16_r231t500cygw.html](url)

ただ、既存のデータパスが ~/data にあったのですが、ここだとどうもうまくいかず、~/public_html/tdiary/data 以下だと動作しています。

また、後者に既存のデータファイルをコピーすると、
`no implicit conversion of nil into String (TypeError)`
になってしまいます。

データのコンバートとか必要だったりするのでしょうか？

＃bundle、gem install は使えなくなっていました。bundle が使えたときがあったのはなぜだったのだろう。

**Comment by mumriks** [comment]
遅くなりましたが、ようやく解決しました。

日記データのキャッシュを生成している間にタイムアウトが発生し、そのためにlatest.rbであるとか201605.rbというファイルが0KBで残ってしまうため、bodyがnilというエラーになったと思われます。
これを削除して生成しなおすことで無事に日記が表示されるようになりました。

ただ、古いparserファイルのものは今後表示させるタイミングで生成しなおすたびにタイムアウトが発生する可能性があり、長年日記などをうかつに表示しようとすると面倒なことになりそうな予感はあるのでした。

とはいえ、ようやく5.0.0で運用できるようになりました。自前のミスともいえる部分が多くてご迷惑をおかけしました。ともあれ、ありがとうございました。

**Comment by tdtds** [comment]
I/Oの遅いcygwinだから重い処理はタイムアウトしてしまうということですかね……。だとすると、Webサーバ側のタイムアウト時間を長めに設定するくらいしか対策は思いつきませんが。

**Comment by mumriks** [comment]
apache のタイムアウトを、120、180、240 と変えて試してみたのですが、いずれも140秒くらいでタイムアウトになってしまうようでした。

ただ、0KBの .rb ファイルを削除してリロードすれば 10 秒ほどで表示できるようにはなりました。.parser ファイルは 200KB 平均くらいです。

プライベートな環境でしか使わないのでかまわない（そもそも Cygwin ですし）のですが、可能であればタイムアウトしたときに 0KB ファイルが残ってしまわないようにできるのであれば nil によるエラーが出ることもないのかなとは思ったりします。

**Comment by tdtds** [comment]
タイムアウトするほど時間がかかるのがそもそもおかしいと思い、キャッシュ周りのコードを見てみたんですが、0byteのファイルができてしまう状況はもしかするとLOCK機構がcygwinで期待通りに動いてないからかも知れません。

自分では使ったことがないのですが、キャッシュそのものを無効にする[tdiary-cache-null](https://github.com/tdiary/tdiary-cache-null)というgemがあります。これを使ってみるといけるかも。

**Comment by mumriks** [comment]
@tdtds 
tdiary-cache-null 試してみました。みごとにタイムアウトすることなく表示することができました！
キャッシュファイルを更新していないデータを確認して試してみたところ数秒程度で表示され、また長年日記を表示させてみても同様に数秒程度で表示されました。
ありがとうございます！

**Comment by tdtds** [comment]
これ以上の対応が不要ならclose願います。

(だいぶCygwin固有の問題の気がするので、tdiary-coreで対応していくのはつらいなー、という感じです)

**Comment by mumriks** [comment]
ありがとうございました。closeしていただければと思います。
