### ISSUE TITLE
amazon.rb のエラーハンドリング中でnilにアクセスしている

### ISSUE THREAD

**Issue by ta-sama** [tdiary/tdiary-core#579]
実際にコードを走らせて確認したわけではないので、間違った指摘をしてしまっていたら申し訳ありません。

5.0.1 で更新された amazon.rb ですが、amazon_get 中の rescue NoMethodError 節で nil に対してメソッド参照しようとしています。以下、該当部分のソースです。

```
   rescue NoMethodError
      message = label || asin
      if @mode == 'preview' then
         if item == nil then
            m = item.nodes( 'Items/Request/Errors/Error/Message' )[0].text
            message << %Q|<span class="message">(#{h @conf.to_native( m, 'utf-8' )})</span>|
         else
            message << %Q|<span class="message">(#{h $!}\n#{h $@.join( ' / ' )})</span>|
         end
      end
```

item == nil の場合なのに、item.nodes を実行しようとしています。そもそもここで取得しようとしている値は item の親要素に存在する値なので、item.nodes ではなく AmazonItem 中の doc から値を取得できるように AmazonItem を拡張 (@doc とかにしてメソッドを追加するとか？) する必要があるかと思います。実際 5.0.0 まではそのようになっていました。

よろしくお願いします。

**Comment by tdtds** [comment]
これはoga対応の余波ですね。どうですか > @hsbt

**Comment by hsbt** [comment]
直しておきます!

**Comment by ta-sama** [comment]
クローズされた後で申し訳ないのですが、修正していただいた内容ではまだ問題が残っているようです。

nil に対するアスセスは今回のパッチで修正されたのですが、item.has_item?  が true だった場合の
`m = item.nodes( 'Items/Request/Errors/Error/Message' )[0].text`
がまずくて、この場合の item には、
`item = AmazonItem.new(xml, parser)`
によって
`@item = doc.elements.to_a( '*/Item' )[0]`
で得られる元のXMLにおける Item ノード以下の情報が格納されるわけですが、Items/Request/Errors/Error/Message という情報は、 Item ノードの親ノードに存在する情報なので、@item 内には存在しません。
よって、item に対して Items/Request/Errors/Error/Message を検索しても必要な情報は絶対に得られず、m には常に "" （空文字列） が代入されることになります。

v.5.0.0 までの amazon.rb では、item に対して Items/Request/Errors/Error/Message を検索するのではなく、root ノード (doc) に対して検索が行われていました。以下、その部分の抜粋です。
```
      doc = REXML::Document::new( REXML::Source::new( xml ) ).root
      item = doc.elements.to_a( '*/Item' )[0]

      ...snip...

         if item == nil then
            m = doc.elements.to_a( 'Items/Request/Errors/Error/Message' )[0].text
                ^^^
```
そもそも、エラーメッセージが取得できなくてもさしたる問題があるわけではないのですが、せっかく修正して頂けるのであればと思い、重ねてご指摘させていただきます。

**Comment by ta-sama** [comment]
すいません、書き間違えました。

> item.has_item? が true だった場合

ではなく、false だった場合、が正しいです。
そもそも .has_item? が false の場合、 .nodes() 中で 結局 nil な @item に対してアクセスしてしまいますので、

> nil に対するアスセスは今回のパッチで修正された

というのも間違った認識でした。

**Comment by hsbt** [comment]
@ta-sama https://github.com/tdiary/tdiary-core/pull/581 こんな感じに `@item` が nil な時は root document から探索するようにしてみたのですがいかがでしょうか?

**Comment by ta-sama** [comment]
はい、これなら問題無く動作するかと思います。

**Comment by tdtds** [comment]
:+1:
