### ISSUE TITLE
終了した raa へのリンクが残っている

### ISSUE THREAD

**Issue by znz** [tdiary/tdiary-core#600]
RAA は 2013 年に終了しています (https://www.ruby-lang.org/ja/news/2013/08/08/rip-raa/ https://www.ruby-lang.org/en/news/2013/08/08/rip-raa/ ) が、 tdiary-core にいくつか RAA へのリンクが存在しているようです ( https://github.com/tdiary/tdiary-core/search?utf8=%E2%9C%93&q=raa&type=Code )。

特に https://github.com/tdiary/tdiary-core/blob/2b6623d6cb69826bf8767e146d79acef03d0e69b/views/footer.rhtml#L4 は一般の tdiary ユーザーのサイトにリンクが出てしまうので、なんとかした方が良いのではないかと思いました。

**Comment by hsbt** [comment]
#601 で直しました

**Comment by hsbt** [comment]
plugin フォルダの下に存在するものは、もう使われてないものも多いので contrib に送ってしまって、きになる人が直すで良さそう。

**Comment by hsbt** [comment]
footer については修正したのでクローズします。報告ありがとうございました!

**Comment by tdtds** [comment]
pluginはコードの修正には及ばないので、ドキュメント中の言及だけ削除する方向で修正。
