### ISSUE TITLE
amp.rb: テーマ情報の保存が古いとエラー

### ISSUE THREAD

**Issue by Nyoho** [tdiary/tdiary-core#615]
`data/tdiary.conf` のテーマ情報 `@conf.theme` が古い形式 (テーマ名のみ) だと、
https://github.com/tdiary/tdiary-core/blob/master/misc%2Fplugin%2Famp.rb#L64 ここで `location` も `theme` も `nil` になってしまい、`amp_theme_css` が `nil` となり、呼び出し元の `.gsub` でエラーとなりました。

一度、テーマを選び直して `@conf.theme` を新しい形式 (`local/themename` の形) にすると、通るようになります。

これはつまり一度テーマを選び直すという作業をしない限りエラーになると思うのでなんらかのコードの変更か、ドキュメントでの注意が必要なのではないかと思いましたのでご報告申し上げたてまつります。

**Comment by tdtds** [comment]
なるほど。これは tdiary.conf の読み込み時に正規化して、プラグインでは意識しないようにすべきですかねぇ。

**Comment by tdtds** [comment]
#616 にて修正の予定

**Comment by tdtds** [comment]
#616 をマージしたのでcloseします。

**Comment by Nyoho** [comment]
ありがたき幸せ🙏
