### ISSUE TITLE
レンサバでindex.rbエラー

### ISSUE THREAD

**Issue by freedomcat** [tdiary/tdiary-core#630]
環境
rbenv 1.1.0-2-g4f8925a
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-freebsd9.1]
https://github.com/tdiary/tdiary-core/releases/download/v5.0.4/tdiary-v5.0.4.tar.gz
を解凍したもの。
bundle install済。

上記環境で次のようなエラーが出力されてtdiaryが動きません。

/home/username/local/rbenv/versions/2.4.1/lib/ruby/2.4.0/cgi/core.rb:618:in `readlines&#39;
/home/username/local/rbenv/versions/2.4.1/lib/ruby/2.4.0/cgi/core.rb:618:in `readlines&#39;
/home/username/local/rbenv/versions/2.4.1/lib/ruby/2.4.0/cgi/core.rb:618:in `read_from_cmdline&#39;
/home/username/local/rbenv/versions/2.4.1/lib/ruby/2.4.0/cgi/core.rb:664:in `initialize_query&#39;
/home/username/local/rbenv/versions/2.4.1/lib/ruby/2.4.0/cgi/core.rb:852:in `initialize&#39;
/home/username/local/tdiary/tdiary-v5.0.4/index.rb:21:in `new&#39;
/home/username/local/tdiary/tdiary-v5.0.4/index.rb:21:in `&lt;top (required)&gt;&#39;
/home/username/local/lib/rubygems/core_ext/kernel_require.rb:55:in `require&#39;
/home/username/local/lib/rubygems/core_ext/kernel_require.rb:55:in `require&#39;
index.rb:4:in `&lt;main&gt;&#39;

**Comment by freedomcat** [comment]
すみません、自己解決しました。

https://246ra.ath.cx/~takasi/tdiary/20130825.html の下記部分を参考にし、
>index.rb と update.rb の shebang 行を rbenv でインストールしたパスに書き換える。（which ruby で出力される /home/foo/.rbenv/shims/ruby ではダメで、実行ファイルそのものの /home/foo/.rbenv/versions/2.0.0-p247/bin/ruby を指定）

versionsの実行ファイルそのものを指定したらうまく動きました。

**Comment by hsbt** [comment]
解決してよかったです!
