### ISSUE TITLE
who is maintain misc/paas/cloudfoundry ?

### ISSUE THREAD

**Issue by tdtds** [tdiary/tdiary-core#653]
セキュリティマターだけどたぶん影響ないので公開でやりますが、`misc/paas/cloudfoundry`に含まれるGemfileに脆弱性のあるバージョンのyajl-ruby gemが指定されていて警告が出ています。

ここ数年アップデートされていないので使われていない可能性が高いのですが、過去このファイルを触っていた @hsbt と @satoryu (だけかな?)で、これらのファイルをアップデートするかメンテをやめる(削除する)か決めてもらえますか。

**Comment by satoryu** [comment]
メンテやめて良いと思います。
自分がもうCFを使わなくなってしまいましたし、CF v1への対応なので現在のv2では動かないと思いますので。

**Comment by hsbt** [comment]
消します! (明日)
