### ISSUE TITLE
Ruby 2.6 対応

### ISSUE THREAD

**Issue by hsbt** [tdiary/tdiary-core#661]
https://github.com/ruby/ruby/commit/c39bdb798d838d58126b548465908243c41bb1fb の影響で tDiary が動かなくなってしまったので、何らかの対策を考えます。

@tdtds @machu 

個人的にはついにこの時が来てしまったかということで 2.6 ないし、全バージョンで $SAFE やめる、が良いと思いますがどうでしょうか。

**Comment by tdtds** [comment]
ruby 3.0まで生き残ると思ってたんだけどなー。

最近はtDiaryを動かす上でも不都合の方が多かったので、なくす方向で良いと思います。今回は`$SAFE == 1`の状況が消えるだけだから、メジャーバージョンはあげなくてもいいかな。
