### ISSUE TITLE
tdiary-v5.0.11.tar.gz と tdiary-full-v5.0.11.tar.gz 内に不要な tdiary-core ディレクトリが含まれている

### ISSUE THREAD

**Issue by kenichiice** [tdiary/tdiary-core#760]
tDiary 5.0.11のリリースファイルの tdiary-v5.0.11.tar.gz を展開すると、 tdiary-core というディレクトリが存在しています。

    $ ls tdiary-v.5.0.11/
    app.json    Dockerfile    lib/          README.md              test/
    benchmark/  dot.htaccess  LICENSE       spec/                  theme/
    bin/        Gemfile       misc/         tdiary.conf.beginner   tmp/
    ChangeLog   Gemfile.lock  package.json  tdiary.conf.sample     update.fcgi*
    config.ru   index.fcgi*   Procfile      tdiary.conf.sample-en  update.rb*
    data/       index.rb*     public/       tdiary-core/           vendor/
    doc/        js/           Rakefile      tdiary.gemspec         views/

そして、tdiary-coreの中にはtdiary-core一式が入っています。

    $ ls tdiary-v.5.0.11/tdiary-core
    app.json    Dockerfile    lib/          README.md              theme/
    benchmark/  dot.htaccess  LICENSE       spec/                  tmp/
    bin/        Gemfile       misc/         tdiary.conf.beginner   update.fcgi*
    ChangeLog   Gemfile.lock  package.json  tdiary.conf.sample     update.rb*
    config.ru   index.fcgi*   Procfile      tdiary.conf.sample-en  vendor/
    data/       index.rb*     public/       tdiary.gemspec         views/
    doc/        js/           Rakefile      test/

このtdiary-coreディレクトリはアーカイブファイルに含まれるべきではないものだと思います。

tdiary-full-v5.0.11.tar.gz の方も同様のようです。

アーカイブファイルが無駄に巨大になるだけで特に問題はないのかもしれませんが、気が付いたので報告いたします。

**Comment by tdtds** [comment]
ありがとうございます。bundlerの動作(?)でこうなってしまうみたいです。パッケージからは除外できないか考えてみますね。

**Comment by kenichiice** [comment]
そうなのですね。ちなみに、私の手元で `bundle exec rake package:stable` を実行したときに作られるアーカイブには余分なtdiary-coreディレクトリは含まれません。環境により挙動が異なるのですかね。

```
% bundle --version
Bundler version 2.0.1

% ruby --version
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]

% ls -l tmp
total 15060
-rw-r--r-- 1 kenichi kenichi   33194 Mar  1 09:59 tdiary-blogkit-v.5.0.11.tar.gz
-rw-r--r-- 1 kenichi kenichi  371466 Mar  1 09:59 tdiary-contrib-v.5.0.11.tar.gz
-rw-r--r-- 1 kenichi kenichi 7500280 Mar  1 09:59 tdiary-full-v.5.0.11.tar.gz
-rw-r--r-- 1 kenichi kenichi 4003059 Mar  1 09:59 tdiary-theme-v.5.0.11.tar.gz
-rw-r--r-- 1 kenichi kenichi 3498567 Mar  1 09:59 tdiary-v.5.0.11.tar.gz

% tar tvf tmp/tdiary-v.5.0.11.tar.gz | grep tdiary-core

```

**Comment by tdtds** [comment]
5.0.12によけいなファイルが含まれないことを確認したのでクローズします。
