### ISSUE TITLE
カテゴリリストの表示時、「新しい順」に並べたい

### ISSUE THREAD

**Issue by kmuto** [tdiary/tdiary-core#845]
カテゴリリストの表示時、現状では「古い順」に並びますが、「新しい順」に並べる設定がほしいです。

現在は手元で

https://github.com/tdiary/tdiary-core/blob/4b4cba73689da09338cf019edc67d73ed1eb49a0/misc/plugin/category.rb#L68

の `flatten(1)`の前に`reverse`を入れて対処しています。

**Comment by tdtds** [comment]
たしかに長期間つけている日記だと、新しい順に見たいことが増えそうですね。検討します。
