### ISSUE TITLE
Please don't publish vendor bundled gems

### ISSUE THREAD

**Issue by mensfeld** [tdiary/tdiary-core#884]
Hey, your rubygems release contains bundled pack: https://rubygems.org/gems/tdiary in vendor dir. You don't have to have it and it makes the releases much bigger and harder to review.

I would appreciate if you would release it without vendor. Thanks! <3

FYI I found it when I've been looking at your release here: https://my.diffend.io/gems/tdiary/5.1.1/5.1.2

**Comment by hsbt** [comment]
We need to publish them because tDiary support no internet environment.

**Comment by mensfeld** [comment]
@hsbt, can you provide me with a bit more info? Publishing to RubyGems and fetching automatically means that you have internet, right? Or is this package distributed differently? I'm asking because I'm curious of the use-case here :)
