### ISSUE TITLE
bundler 2.0.2 が無い

### ISSUE THREAD

**Issue by yutopia** [tdiary/tdiary-core#899]
ロリポップのサーバーが何年かぶりにアップグレードして、これまで ruby 2.0 だったのが一挙に 2.6 に上がりました。
それにともない tDiary も最新のものにアップデートしようとしました。

tdiary-full-v5.1.2.tar.gz を使いました。
ロリポップ固有の条件(index.rbとupdate.rbのシェバンをrubyのパスに合わせて変更するのと、.htaccess の設定)をした後、データと画像だけを tDiary 5.1.2 に移してサーバーにアップロードしました。

そこで日記を表示しようとしたところ、bundler の 2.0.2 が無いとおこられました。(すみません、正確なメッセージは忘れました。)
調べてみると、misc/lib/bundler-2.1.4 はあるのですが、実行時にこれを見に行ってエラーになったようです。

以前ダウンロードしてあった  tdiary-full-v5.1.1.tar.gz には misc/lib/bundler-2.0.2 があり、こちらを使うと日記は表示されるようです。

手元の環境では ruby のバージョンを再現できなかったので確認できてないのですが、tar ball を作るときに INSTALL-cgi.md にある bundle の実行に問題があったのではと推測しています。

**Comment by tdtds** [comment]
ありがとうございます、調査します！

**Comment by tdtds** [comment]
本日リリース予定の 5.1.3 にバンドルする bundler を 2.1.4 に戻しました。
