### ISSUE TITLE
set default branch name to "master"

### ISSUE THREAD

**Issue by tdtds** [tdiary/tdiary-core#900]
[Set the default branch for newly-created repositories](https://github.blog/changelog/2020-08-26-set-the-default-branch-for-newly-created-repositories/) でアナウンスがあったように、GitHubでは10月1日以降のデフォルトブランチ名が`main`になりますが、同じorg内で異なるデフォルトブランチのリポジトリが混在するのは悪夢なので、tDiary orgではデフォルトブランチを従来どおり`master`にするように設定しようと思います(というか忘れないうちにしてあります)。

**Comment by hsbt** [comment]
賛成ですー。
