### ISSUE TITLE
image.rb が ogp.rb 内 apply_plugin 関数から処理される場合にファイル名が欠ける

### ISSUE THREAD

**Issue by yukinobu** [tdiary/tdiary-core#914]
はじめまして。tDiary を長く使わせてもらっています → https://www.yukinobu.jp/tdiary/

## 不具合の説明

See Also: https://twitter.com/yukinobu/status/1345219280728588295

tDiary 5.1.4 で `image.rb` と `ogp.rb` を組み合わせて使用したのですが、`og:image` がうまく出力されませんでした。次の [A] のように、`.jpg` までのファイル名が出力されることを期待したのですが、実際には [B] のようにディレクトリまでしか出力されず、ファイル名が欠けていました。

**[A] 期待した出力：**

```html
<meta property="og:image" content="https://www.yukinobu.jp/tdiary-v5.1.4-test/images/20210102_0.jpg">
```

**[B] 実際の出力：**

```html
<meta property="og:image" content="https://www.yukinobu.jp/tdiary-v5.1.4-test/images/">
```

原因を探る中で、`ogp.rb` 内で `apply_plugin` 関数を使用する際に、`image.rb` 部分は次のように処理されることが判りました（[C]～[E]）。

**[C] `ogp.rb` 内で `apply_plugin` 関数を使用する部分：**

```ruby
section_html = apply_plugin(section)
```

**[D] `apply_plugin` 関数への入力（`section` 変数）：**

```
<%=image 0, '画像の説明', nil, [1848,2157]%>
```

**[E] `apply_plugin` 関数の出力（`section_html`変数）：**

```html
<img class="photo" src="https://www.yukinobu.jp/tdiary-v5.1.4-test/images/" alt="画像の説明" title="画像の説明" width="1848" height="2157">
```

この [E] では、[B] と同様にファイル名部分が欠けています。一方、tDiary がブラウザに出力する HTML では、[E] の部分は次の [F] のようになっており、ファイル名部分が存在します。

**[F] tDiary がブラウザに出力する HTML：**

```html
<img class="photo" src="https://www.yukinobu.jp/tdiary-v5.1.4-test/images/20210102_0.jpg" alt="画像の説明" title="画像の説明" width="1848" height="2157">
```

[E] と [F] の比較から、[D] のような `image.rb`プラグインの呼び出しは、tDiary がブラウザに出力する処理フローでは問題ないものの、`ogp.rb` 内で `apply_plugin` 関数を使用する際は異なる結果を生じるようです。

## 原因の推測

`image.rb`プラグインの `image` 関数が呼び出される際、処理フローによっては `@image_date` 変数が正しく設定されないケースがあるのではと推測しています。`@image_date` 変数は、`image` 関数の冒頭で、次の [G] のように `image` 変数および `image_t` 変数を初期化するのに使用されています。

**[G] `image` 関数の冒頭：**

```ruby
def image( id, alt = 'image', thumbnail = nil, size = nil, place = 'photo' )
  	image = image_list( @image_date )[id.to_i]
  	image_t = image_list( @image_date )[thumbnail.to_i] if thumbnail
```

`image` 変数および `image_t` 変数は、次の [H] のように `img` タグを出力する部分で使用されています。

**[H] `image` 関数内の `img` タグ出力部分：**

```ruby
	if thumbnail then
	  	%Q[<a href="#{h @image_url}/#{h image}"><img class="#{h place}" src="#{h @image_url}/#{h image_t}" alt="#{h alt}" title="#{h alt}"#{size}></a>]
	else
		%Q[<img class="#{h place}" src="#{h @image_url}/#{h image}" alt="#{h alt}" title="#{h alt}"#{size}>]
	end
```

`@image_date` 変数の値が正しくない場合、`image` 変数および `image_t` 変数も正しくない値（おそらくは空文字列）となるので、本来 [F] を出力して欲しいところ、[E] の出力となる現象を説明できそうです。

## 修正案（要改善）

ここで、`image.rb` プラグイン内の `image` 関数の冒頭に次の [I] のコードを追加し、`@image_date` 変数を `@date` に基づき初期化するようにします。

**[I] `image` 関数の冒頭への追加コード：**

```ruby
@image_date = @date.strftime( "%Y%m%d" )
```

このような修正をしたところ、[B] の出力は [A] のように、[E] の出力は [F] のように変化し、本問題の解決に効果があることが判りました。

ただし、この修正をした状態では、個別の日付の日記を開くケース（tDiary に `?date=20210102` などの引数をつけるとき）は問題ないものの、複数の日付の日記を同時に開くケース（tDiary に何も引数をつけないとき）は、うまく動作しませんでした（たとえば 1/1～1/2 の日記を同時に開くケースでは、すべての日記に 1/2 の画像が表示されました）。

このため、この修正案はそのままでは使用できず、より正しい方法で `@image_date` 変数を設定する必要があると考えています。

## 回避策

`image.rb` プラグインの代わりに `image_ex.rb` プラグインを有効にした状態では、[B] および [E] の出力は、次の [J] および [K] のように変化しました。

**[J] `image_ex.rb` プラグインを有効にした状態での [B]**

```html
<meta property="og:image" content="./images/20210102_0.jpg">
```

**[K] `image_ex.rb` プラグインを有効にした状態での [E]**

```html
<img src="./images/20210102_0.jpg" alt="画像の説明" title="画像の説明" width="[1848, 2157]" class="image-ex none">
```

[J], [K] ともファイル名が含まれますので、本問題の回避策として `image_ex.rb` プラグインが使用できるかも知れません。また、`image_ex.rb` プラグインでは本問題は生じないことから、本問題は `image.rb` プラグイン特有の問題かと思われます。

## テスト環境

本問題のテスト用に tDiary を立てています。認証付きで、ユーザ名パスワードとも `guest` です。編集や設定変更をしていただいても構いません。

https://www.yukinobu.jp/tdiary-v5.1.4-test/

この日記は tdiary-v5.1.4.tar.gz から作成しました。初期状態から変更した点は以下です。

* tdiary-contrib-v5.1.4.tar.gz より ogp.rb を misc/plugin/ogp.rb としてコピーしました
* プラグインとして image.rb と ogp.rb を有効化しました
* テスト用に画像入りの日記を書きました
  * https://www.yukinobu.jp/tdiary-v5.1.4-test/?date=20210102
  * https://www.yukinobu.jp/tdiary-v5.1.4-test/?date=20210101

#### サーバ

* tDiary 5.1.4
* Ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
* Apache HTTP Server 2.4.41-4ubuntu3.1
* Ubuntu 20.04.1 LTS

#### クライアント

* Firefox 84.0.1
* Windows 10 [20H2]

**Comment by tdtds** [comment]
詳細なレポートありがとうございます！ 問題は再現できましたので、これから修正にとりかかりますね。

**Comment by tdtds** [comment]
contrib/plugin/ogp.rb の方で修正してみました。ご確認いただけますか? tdiary/tdiary-contrib#234
直っているようなら、次のリリースに取り込みます。

**Comment by yukinobu** [comment]
早速の対応、ありがとうございます。

[テスト用の日記](https://www.yukinobu.jp/tdiary-v5.1.4-test/?date=20210102)にて、確認したところ、期待する出力が得られました。

**修正前の `og:image` 出力：**

```html
<meta property="og:image" content="https://www.yukinobu.jp/tdiary-v5.1.4-test/images/">
```

**修正後の `og:image` 出力：**

```html
<meta property="og:image" content="https://www.yukinobu.jp/tdiary-v5.1.4-test/images/20210102_0.jpg">
```

また、[私の日記](https://www.yukinobu.jp/tdiary/?date=20210101)にも同様に適用し、上記と同様の期待する出力が得られました。

加えて、`og:image` を使用するクライアントとして以下を試しましたが、いずれのクライアントでも日記内の画像が使用される形となりました（意図した動作です）。

* Safari（iOS、共有ボタン使用時）
* Twitter（iOS、新規Tweet画面）
* Skype（Windows、チャットウィンドウ）
* Facebook（Web、投稿を作成）

また、私の当初の修正案にあったような、有害な副作用も無いようです。

全体として、修正は問題なく機能していると思います。ありがとうございました！
