### ISSUE TITLE
calendar2.rb は【前n日分】表示モードで日記のある日を認識しないことがある

### ISSUE THREAD

**Issue by yukinobu** [tdiary/tdiary-core#918]
## 不具合の説明

tDiary 5.1.4 で `calendar2.rb` プラグインを使用する際、【前n日分】表示モードではカレンダーが日記のある日を認識せず、リンクが付かない場合があるようです。実例は[異常な場合](#異常な場合)を参照ください。

### 事前準備

tDiary 5.1.4 で次の準備をします。

1. `calendar2.rb` プラグインを有効にします。
2. ヘッダの設定で、同プラグインを使用したカレンダーが表示されるようにします。

   **[A] ヘッダの設定（抜粋）：**

   ```ruby
   <%=calendar2%>
   ```

3. 次の日付について日記を書きます。

   * 2021/01/05
   * 2021/01/03
   * 2020/12/25
   * 2020/12/23

4. 設定項目【最新表示の最大日数】を2とします。その結果、`data/tdiary.conf` は以下のようになります。

   **[B] `data/tdiary.conf` （抜粋）：**

   ```ini
   latest_limit = 2
   ```

### 正常な場合

tDiary を、何も引数を付けずにブラウザで読み込みます。カレンダーは次のようになり、1月に書いた日記を正しく認識し、日記がある日にリンクを付けて表示します。

**[C] 2021年1月のカレンダー表示（正常）：**

![clip_20210105_100722](https://user-images.githubusercontent.com/5938690/103595825-cc0efb80-4f3f-11eb-8341-605b83a43681.png)

ここで、カレンダーの【前】リンクを開きます。すると tDiary には引数 `?date=202012` が付加されます。この時、カレンダーは次のようになり、12月に書いた日記を正しく認識し、日記がある日にリンクを付けて表示します。

**[D] 2020年12月のカレンダー表示（正常）：**

![clip_20210105_100740](https://user-images.githubusercontent.com/5938690/103595846-daf5ae00-4f3f-11eb-8c8a-a9282553be39.png)

### 異常な場合

tDiary を、何も引数を付けずにブラウザで読み込んだ後、ヘッダの【«前2日分】リンクを開きます。すると tDiary には引数 `?date=20201225-2` が付加されます。この時、カレンダーは次のようになります。

**[E] 2021年1月のカレンダー表示（異常）：**

![clip_20210105_100823](https://user-images.githubusercontent.com/5938690/103595861-e34de900-4f3f-11eb-8b3d-b78edb7208f8.png)

このカレンダーは、次の点で[正常な場合](#正常な場合)とは異なり、異常と感じられます。

1. 2020年12月以前の日記を表示しているにもかかわらず、カレンダーは異なる月（1月）を表示している。
2. カレンダーが表示している月（1月）について、既に書いた日記を正しく認識しておらず、日記がある日にリンクがない。

期待する挙動としては、[C] または [D] のカレンダーが表示される形です。どちらかと言えば [D] が良いと思います。

## 原因の推測

`calendar2.rb` 内 `calendar2` 関数の、次の部分に原因があると推測しましたが、詳細は判りませんでした。

```ruby
    date = if /^(latest|search)$/ =~ @mode
                Time.now
            else
                @date
            end
    year = date.year
    month = date.month
```

## テスト環境

本問題のテスト用に tDiary を立てています。認証付きで、ユーザ名パスワードとも `guest` です。編集や設定変更をしていただいても構いません。

https://www.yukinobu.jp/tdiary-v5.1.4-test-2/

この日記は tdiary-v5.1.4.tar.gz から作成し、[事前準備](#事前準備)項目に記載の点を変更しました。

#### サーバ

* tDiary 5.1.4
* Ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
* Apache HTTP Server 2.4.41-4ubuntu3.1
* Ubuntu 20.04.1 LTS

#### クライアント

* Firefox 84.0.1
* Windows 10 [20H2]

**Comment by tdtds** [comment]
calendar2はかなり古いプラグインなので、いろいろ想定していない状況がありますね。 #921 で修正してみました。いかがでしょうか。

**Comment by yukinobu** [comment]
テスト環境および、私の日記にて確認しました。
問題は再現しなくなり、正常な挙動になったと思います。修正ありがとうございました！

**Comment by tdtds** [comment]
確認ありがとうございます！ ではmergeしますね。
