### ISSUE TITLE
Herokuへのデプロイ時Configure environmentでスタックする

### ISSUE THREAD

**Issue by eggplants** [tdiary/tdiary-core#952]
**Describe the bug / 不具合の説明**

tdiary/tdiary-core#masterのHerokuへのデプロイ時にConfigure environmentから進まなくなる。

**To Reproduce / 再現手順**

1. [![Deploy](https://www.herokucdn.com/deploy/button.png)](https://www.heroku.com/deploy?template=https://github.com/tdiary/tdiary-core)をクリック
2. 各種項目を記入
3. ![image](https://user-images.githubusercontent.com/42153744/129175695-63d21fb9-912c-4439-899a-d9ebb8f5d0e0.png)をクリック
4. デプロイが開始されるがConfigure environmentのステップで進まなくなる。

(1日放置してみましたがダメでした)

**Environment / 動作環境**
 - OS: Ubuntu Desktop 21.04
 - Browser: Chrome 91.0.4472.77(Official Build)(64 bit)
 - tDiary Version: master/ 5e9f21a701b9d2dc83e58c0f8a9ec1e66f1b5529

**Comment by tdtds** [comment]
MongoDBのURIを指定しなければいけなくなっていたのに対応できていませんでした。🙇‍♂️

※HerokuからリーズナブルなMongoDBのadd-onがなくなってしまったので、MongoDB Atlasなどの外部DaaSを使う必要があります。
